### DISCUSSION TITLE
Release 6 disussion

### DISCUSSION THREAD

**Discussion by PeterH24x7** [PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring#17] [Announcements]
The release-ready code is now in the main github code tree (links below) and includes a 3-phase and advanced version for your interest. The advanced version of the code includes additional sensors that are applicable to my single-phase 6-channel set-up (and any user with the same), else will this will need customising by someone with more advanced HA YAML skills.

I plan on formalising the release 6 in the next days.

solar_analytics - regular code base for release 6
https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/blob/main/solar_analytics.yaml

solar_analytics_3phase - 3 phase code base for release 6
https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/blob/main/solar_analytics_3phase.yaml

solar_analytics_advanced - advanced code base for release 6
https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/blob/main/solar_analytics_advanced.yaml

**Comment by PeterH24x7** [comment]
Release 6 (as 6.2) now published. Discussions about this release welcomed here!

**Comment by PeterH24x7** [comment]
Some strange data as shown below received for my **sa_data_by_5min_...** get today. First record **[0]** contains '**null**' data for **energy_generated**, **energy_consumed** etc. Error checking introduced for Release 6 checks the get to ensure there are valid numbers (as is_number) and if not all related sensors are determined to be **'unavailable'**. Subsequent records beyond **[0]** from the get appear to operate as normal. 

![sa_null_first_record-30Aug23](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/91523850/b7e8dfb1-dcbc-4377-88fc-9f273c50a0c1)

I have created a work around fix that checks the second record **[1]**, if the first **[0]** is null. Example code as follows but wider changes to all related sensors were also required. Keen to know if others experienced the same? Will test and publish update soon.

```
      - name: sa_data_by_5min_energy_consumed
        unique_id: sa_data_by_5min_energy_consumed
        value_template: >
          {%- if (value_json is defined) 
              and (value_json.data[0].energy_consumed|is_number 
                or value_json.data[1].energy_consumed|is_number) 
            -%}
            {%- set most_recent_sensor_data = value_json['data'] | rejectattr('energy_consumed', 'equalto', None) | list | last -%}
              {{- most_recent_sensor_data.energy_consumed 
                  if most_recent_sensor_data.energy_consumed|float(0.0) > 0.0
                  else 0.0 
                -}}
          {%- else -%}
            {{- states.sensor.sa_data_by_5min_energy_consumed.state|default(0.0) -}}
          {%- endif -%}
```

**Reply by PeterH24x7** [reply]
For reference, heres the code to debug the issue and see the results as shown above (borrowed from Release 4).

```
  - platform: rest
    name: sa_data_by_5min
    resource_template: https://portal.solaranalytics.com.au/api/v2/site_data/{{ states('input_text.sa_site_id') }}?all=true&gran=minute&trunc=false&power=false&tstart={{ now().strftime("%Y%m%d") }}&tend={{ now().strftime("%Y%m%d") }}   
    username: !secret sa_username
    password: !secret sa_password
    authentication: basic
    value_template: >-
      {% set most_recent_sensor_data = value_json['data'] | rejectattr('energy_consumed', 'equalto', None) | list | last %}
        {{ most_recent_sensor_data.t_stamp }}    
    json_attributes:
      - "data"
    scan_interval: 300
```

**Reply by Roving-Ronin** [reply]
@PeterH24x7 what version of HA are you using ? I'm on the latest 2023.8.4 and filter by sa_data_by_5min and get all these:

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/108674933/ae9b4c98-ffaa-4c0b-ae88-182791b17e4e)

But otherwise the consumed / generated etc is working for me on v6.2

**Reply by PeterH24x7** [reply]
Hi @Roving-Ronin  - That's right - your list is all the sensors that were "unavailable" due to the Solar Analytics data anomaly I've described above. Ordinarily, the SA API would not be providing a day's first 5 mins data as "null", and remain so for the whole day. As a result these sensors remained "unavailable" until I found the problem and made the fix; but it would likely have nonetheless fixed itself on the next day's restart (with new data and no "null" first entry).  I'm otherwise on the latest version of HA. 

Otherwise, from your list above it looks like you're not using the 3-phase version - where **load_ev_charger**, **load_air_conditioner**, **load_hot_water** and **load_stove** are all defined, but "unavailable". If so, it's good to see that the code works as expected even if the data isn't available. Maybe we don't need a separate 3-phase version?

**Reply by Roving-Ronin** [reply]
@PeterH24x7 no I'm definitely using the 3 phase version of the code, triple checked that and there's no sensors etc defined for air_conditioning / ev_charger / hot_water / stove... only mention of those words even is only the in comments text, but not the actual yaml code. Has me scratching my head and can't seem to delete it by going to Developer Tools --> Statistics either.  Look them up in Settings --> Entities and they don't exist there, just in the States view.

**Comment by Roving-Ronin** [comment]
Hi @PeterH24x7,
Just wondering if it would be possible and of value to everyone, to add a check to see if SA is receiving data from a site? If the SA API doesn't specifically have a status = offline / no data function in it, thinking maybe could instead use a 'if status is offline/unknown, for greater than x hours' then declare the site offline?

From this notifications could then be configured, or have some card with red/green status for SA..?

Wondering about this as just found my KR-63 modem had been offline since 11th Oct (a "lifetime subscription" site on 4G network with mobile network being blamed, but magically works after SA 'reset the SIM'. The SIM is in the KR-63 and how can you do that unless it has connectivity. The cynic in me wonders if all lifetime users SIM's where disabled, to see who is still using their SA installation / who notices, and if you noticed and shouted out then SA unblocked and continued to pay for the SIM... all conjecture but a bit suspect).

**Reply by Luke47-Dev** [reply]
Yes please! Mine has a habit of randomly dropping off. I've turned on notifications via their portal for device offline, however never seen it work....

**Reply by PeterH24x7** [reply]
@Roving-Ronin and @SimoHDK - keen to help, but I think I need some more info to understand what you are looking for as I've not had such issues myself. Is the sensor **sa_dashboard_status** correlated with what you are after? Is there something on the Solar Analytics end-user portal, if so can you show a screen grab?
Rgds, Peter

**Reply by Luke47-Dev** [reply]
Hi Peter,

It's typically generated by these Communication Fails - As you can see highlighted, recently mine was offline and on the 4th day I realised, and rebooted the KR63 - Then back to normal. 

I'll try power down the KR63 tomorrow manually and see how long it takes for the dashboard to reflect (if anything) - the sa_status may already be working and I hadn't thought about it till Ronin's comment.

<img width="521" alt="Screenshot 2023-10-20 at 10 28 53 pm" src="https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/17811281/bd4ba5c6-ac7f-4107-a9c7-38bb9a2b49f2">

**Reply by PeterH24x7** [reply]
Hi @SimoHDK and @Roving-Ronin -

I've dug into the SA user portal code and worked out how to retrieve the "system log" as shown above; where no such thing is described in the SA public API. 

Below is the rest **resource_template** code that defines a new sensor **sa_status_log_entry** which is the latest system log entry's "fault status", plus other data as attributes. Insert this block of code under the "rest:" definition - e.g. after the **sa_status** sensor definition.

Let me know if this is what you're looking for.

```
  - resource_template: https://portal.solaranalytics.com.au/api/v4/site_status/{{- states('input_text.sa_site_id') -}}?event_group=all
    headers: 
      Authorization: >
        {{- 'Bearer ' ~ state_attr('sensor.sa_auth_token','token') -}}
    scan_interval: 300
    sensor:
      - name: sa_status_log_entry
        unique_id: sa_status_log_entry
        value_template: >
          {{- value_json.data.event_list[0].fault_status -}}
        json_attributes_path: "$.data.event_list.[0]"
        json_attributes:
          - "event_id"
          - "start_timestamp"
          - "end_timestamp"
          - "last_updated_at"
          - "severe_tag"
          - "event_type"
          - "fault_type"
          - "fault_class"
```

**Reply by Luke47-Dev** [reply]
Hi Peter - Tested and working! Too good! Here's my findings.

1. I turned off power to the KR63 and waited for a state-change...
2. After 90-minutes, SA updated to say 'Communication Offline' - Must be a wait period to reduce false alarms, however still a long and annoying timeframe nonetheless

<img width="1069" alt="Screenshot 2023-10-22 at 9 25 32 pm" src="https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/17811281/29c7e6e7-f668-40c4-8306-303f70139624">

3. It in turn presented the fault status in HA as "Action_owner" 

<img width="564" alt="Screenshot 2023-10-22 at 9 25 48 pm" src="https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/17811281/2b1d7f8b-fdf2-4b8f-80ef-8cac8c393b32">

4. With a little more digging, I can see that 'Action_owner' ties in with the instructions here to reboot the unit.

<img width="1076" alt="Screenshot 2023-10-22 at 10 07 49 pm" src="https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/17811281/b2ec4a61-2013-4b17-9612-d4224070540a">

Disappointingly, no SA emails during this period to alert me to a fault. So will be creating a simple automation to pushover notify me. If it's anything other than 'resolved' we have a problem.

Any ideas what the other 'states' are?

**Reply by Roving-Ronin** [reply]
Apologies for the lack of reply after the request, still trying to recover from some bug that has laid me low for the last week and now still feeling drained and head a bit wonky.

Here's the fault type I have for my last outage:
Event type:    fault
Fault type:     communications    
Fault clas:      communications_fault

Though I note the following other messages in my SA portal (not the new REST sensor in HA) for prior outages. 
- Moderate Under-Performance 
- Zero Energy Production


Pending feeling better to have a 'proper' go at this, it looks like this rest sensor could work fine, but just add a template sensor to provide from easier to understand mappings. Below is just a mock up, pending knowing what the full list of fault status messages:


```
template:
  sensor:
    - name: Solar Analytics Connnection Status
      unique_id: sa_connection_status
      state: >
        {% set connection_status = states('sensor.sa_status_log_entry') %}
        {% if connection_status|lower == 'resolved' %}
          No Issues
        {% elif connection_status|lower == 'Action_owner' %}
          Connection failed reset SA modem
        {% elif connection_status|lower == 'moderate_under_production' %}   #This is just a made up error code for example
          Solar Plant Low Production
        {% elif connection_status|lower == 'zero_energy_production' %}   #This is just a made up error code for example
          Solar Plant No Production
        {% elif connection_status|lower == 'unavailable' %}
          API not available
        {% else %}
          {% if connection_status %}
            {{ connection_status }} was returned
          {% else %}
            Error
          {% endif %}
        {% endif %}
```

Using this would allow us to generate some messages that are eaiser to understand, tell users what needs to be done. Also we could add an automation for sending notifications (in this case to to HA app on an iPhone).

```
automation:
  - id: '1234567890xxxxxx'
    alias: Notify - Solar Analystics Availability
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.sa_connection_status
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.sa_connection_status
            enabled: true
            state: No Issues
          - condition: state
            entity_id: sensor.sa_connection_status
            state: API not available
    action:
      - service: notify.mobile_app_xxxxxxxx_iphone_14
        data:
          title: Solar Analytics Status Change
          message: >-
            Solar Analytics status just changed from "{{ trigger.from_state.state }}" to "{{trigger.to_state.state }}"
          data:
            priority: high

```
