### DISCUSSION TITLE
Assistance please

### DISCUSSION THREAD

**Discussion by wilsoac** [PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring#26] [Q&A] [answered]
Hi Peter,

I am new to HA and I am trying to set up this configuration in my HA but I am getting a couple of errors. I'm not sure if this is the place to get assistance but I cant seem to find anywhere else with info. Whilst your documentation is fantastic I am too new to fully understand the process and some information I need is assumed knowledge! So far I have added my user, PW and site to the secrets Yaml. Added the solar_analytics_advanced.yaml and tried to add the packages in the default config (I think this is where I am getting the error)

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
packages: !include solar_analytics_advanced.yaml

![WhatsApp Image 2024-10-20 at 21 46 12_57e86d3f](https://github.com/user-attachments/assets/79412968-0310-4bdb-962a-c65b8a201735)

Again, I am pretty green with all of this and also understand your time is valuable. If you are able to give me a hand that would be appreciated. If not could you please point me to a place where I can get some additional information.

Kind regards,

Andrew

**Comment by PeterH24x7** [comment]
Hi @wilsoac - happy to help. This is an extract of my **configuration.yaml**. It looks like you've left off a label for the **packages** (e.g. pack_1 in my case - but other names also work). Make sure you get the indentation right. Also, you may wish to start with the simple 3-phase version (consumption and generation channels only) to prove it's working okay. If you have other channels than those I have configured (i.e. **load_air_conditioner**, **load_hot_water**, **load_ev_charger** and **load_stove**) please let me know.

Chrs, Peter

```
homeassistant:  
  external_url: "https://yourdomain.net/"
  internal_url: "http://192.0.0.146:8123"

  country: AU

  packages:
    pack_0: !include gates.yaml
    pack_1: !include solar_analytics.yaml
    pack_2: !include influxdb.yaml
    pack_3: !include weather_extras.yaml
```
