### ISSUE TITLE
Use Solar Analytics sourced data to report Consumed, Generated and Import-Export Power (W)

### ISSUE THREAD

**Issue by PeterH24x7** [PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring#1]
The SA public API unfortunately does not provide any real/near-real time power data. However, the current day's energy data by 5 minute intervals can be obtained every 5 minutes (as used for the total energy consumed, generated, imported and exported). The average power during the 5 minute interval is equal to 12 x energy used in 5 minutes (where there are 12x 5-minute intervals in an hour).

Working/proposed code to be added to the main code, and yet to be optimised, is as follows:

```
      sa_consumption_power:
        friendly_name: Power Consumption
        unit_of_measurement: "W"
        value_template: >      
          {% set sa_ns = namespace(latest=-1) %}
          {% for count in range(0,287) %}
            {% if (sa_ns.latest == -1) %}
              {% if (states.sensor.sa_data_by_5min.attributes.data[count].energy_consumed) == None %}
                {% set sa_ns.latest = count-1 %}
                {% if (sa_ns.latest >= 0) %}
                  {{ states.sensor.sa_data_by_5min.attributes.data[sa_ns.latest].energy_consumed * 12 }}
                {% else %}
                  {{ 0 }}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endfor %}
        icon_template: mdi:home-lightning-bolt-outline
        device_class: "power"
        attribute_templates:
          state_class: measurement
      sa_generation_power:
        friendly_name: Power Generation
        unit_of_measurement: "W"
        value_template: >      
          {% set sa_ns = namespace(latest=-1) %}
          {% for count in range(0,287) %}
            {% if (sa_ns.latest == -1) %}
              {% if (states.sensor.sa_data_by_5min.attributes.data[count].energy_generated) == None %}
                {% set sa_ns.latest = count-1 %}
                {% if (sa_ns.latest >= 0) %}
                  {{ states.sensor.sa_data_by_5min.attributes.data[sa_ns.latest].energy_generated * 12 }}
                {% else %}
                  {{ 0 }}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endfor %}
        icon_template: mdi:transmission-tower-import
        device_class: "power"
        attribute_templates:
          state_class: measurement
      sa_import_export_power:
        friendly_name: Power Import Export
        unit_of_measurement: "W"
        value_template: >      
          {% set sa_ns = namespace(latest=-1) %}
          {% for count in range(0,287) %}
            {% if (sa_ns.latest == -1) %}
              {% if (states.sensor.sa_data_by_5min.attributes.data[count].energy_generated) == None %}
                {% set sa_ns.latest = count-1 %}
                {% if (sa_ns.latest >= 0) %}
                  {{ (states.sensor.sa_data_by_5min.attributes.data[sa_ns.latest].energy_consumed - states.sensor.sa_data_by_5min.attributes.data[sa_ns.latest].energy_generated) * 12 }}
                {% else %}
                  {{ 0 }}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endfor %}
        icon_template: mdi:solar-power
        device_class: "power"
        attribute_templates:
          state_class: measurement

```

**Comment by 123go** [comment]
I don't know about "optimised" but this style for the value_template is definitely simpler (in my opinion):

```value_template: >
  {% set most_recent_sensor_data = states.sensor.sa_data_by_5min.attributes.data | rejectattr('energy_consumed', 'equalto', None) | list | last %}
  {{ most_recent_sensor_data.energy_consumed }}```

Glen

**Comment by PeterH24x7** [comment]
Hi Glen - thank you as always for your templating expertise. 

The requisite code has now been updated for **sa_consumption_power** and **sa_generation_power**. I've also similarly modified the state value for the **sa_data_by_5min** to be the latest energy **t_stamp**, rather than the previously used "**now()**" time of the get. This state value is then used as a **time_stamp** attribute to each of the energy and power related sensors. Where "**2022-01-13 11:15:00**" is the time_stamp for data generated between "**2022-01-13 11:15:00**" and "**2022-01-13 11:19:59**". Lastly I've greatly simplified the value template for **sa_import_export_power**.

Here's the complete update for the 5 minute data sensor related section. It all seems to be working as expected.

```
# Solar Analytics - get detailed 5 minute data 
# Used to calculate today's total energy for consumed, generated, imported and exported energy for the HA Energy module
# Updated every 5 minutes
  - platform: rest
    name: sa_data_by_5min
    resource_template: 'https://portal.solaranalytics.com.au/api/v2/site_data/36303?gran=minute&tstart={{ now().strftime("%Y%m%d") }}&tend={{ now().strftime("%Y%m%d") }}'   
    username: !secret sa_username
    password: !secret sa_password
    authentication: basic
    value_template: >-
      {% set most_recent_sensor_data = value_json['data'] | rejectattr('energy_consumed', 'equalto', None) | list | last %}
        {{ most_recent_sensor_data.t_stamp }}    
    json_attributes:
      - "data"
    state_class: measurement
    device_class: energy
    scan_interval: 300
    force_update: true

  - platform: template
    sensors:
      sa_todays_energy_consumed_total:
        friendly_name: Total Energy Consumed
        unit_of_measurement: "Wh"
        value_template: "{{ states.sensor.sa_data_by_5min.attributes.data | rejectattr('energy_consumed', 'equalto', None) | sum(attribute='energy_consumed') }}"
        icon_template: mdi:home-lightning-bolt-outline
        device_class: "energy"
        attribute_templates:
          state_class: total_increasing
          time_stamp: "{{ states.sensor.sa_data_by_5min.state }}"
      sa_todays_energy_generated_total:
        friendly_name: Total Energy Generated
        unit_of_measurement: "Wh"
        value_template: "{{ states.sensor.sa_data_by_5min.attributes.data | rejectattr('energy_generated', 'equalto', None) | sum(attribute='energy_generated') }}"
        icon_template: mdi:solar-power
        device_class: "energy"
        attribute_templates:
          state_class: total_increasing
          time_stamp: "{{ states.sensor.sa_data_by_5min.state }}"

      sa_todays_energy_imported:
        friendly_name: Total Energy Imported
        unit_of_measurement: "Wh"
        value_template: >
          {% set energy = namespace(imported=0) %}
          {% for sensor_data in states.sensor.sa_data_by_5min.attributes.data | rejectattr('energy_consumed', 'equalto', None) if sensor_data.energy_consumed > sensor_data.energy_generated %}
            {% set energy.imported = energy.imported + sensor_data.energy_consumed - sensor_data.energy_generated %}
          {% endfor %}
          {{ energy.imported }}
        icon_template: mdi:transmission-tower-export
        device_class: "energy"
        attribute_templates:
          state_class: total_increasing
          time_stamp: "{{ states.sensor.sa_data_by_5min.state }}"
      sa_todays_energy_exported:
        friendly_name: Total Energy Exported
        unit_of_measurement: "Wh"
        value_template: >
          {% set energy = namespace(exported=0) %}
          {% for sensor_data in states.sensor.sa_data_by_5min.attributes.data | rejectattr('energy_generated', 'equalto', None) if sensor_data.energy_generated > sensor_data.energy_consumed %}
            {% set energy.exported = energy.exported + sensor_data.energy_generated - sensor_data.energy_consumed %}
          {% endfor %}
          {{ energy.exported }}
        icon_template: mdi:transmission-tower-import
        device_class: "energy"
        attribute_templates:
          state_class: total_increasing
          time_stamp: "{{ states.sensor.sa_data_by_5min.state }}"

      sa_consumption_power:
        friendly_name: Power Consumption
        unit_of_measurement: "W"
        value_template: >      
          {% set most_recent_sensor_data = states.sensor.sa_data_by_5min.attributes.data | rejectattr('energy_consumed', 'equalto', None) | list | last %}
            {{ most_recent_sensor_data.energy_consumed * 12 }}
        icon_template: mdi:home-lightning-bolt-outline
        device_class: "power"
        attribute_templates:
          state_class: measurement
          time_stamp: "{{ states.sensor.sa_data_by_5min.state }}"
      sa_generation_power:
        friendly_name: Power Generation
        unit_of_measurement: "W"
        value_template: >      
          {% set most_recent_sensor_data = states.sensor.sa_data_by_5min.attributes.data | rejectattr('energy_generated', 'equalto', None) | list | last %}
            {{ most_recent_sensor_data.energy_generated * 12 }}
        icon_template: mdi:transmission-tower-import
        device_class: "power"
        attribute_templates:
          state_class: measurement
          time_stamp: "{{ states.sensor.sa_data_by_5min.state }}"

      sa_import_export_power:
        friendly_name: Power Import Export
        unit_of_measurement: "W"
        value_template: >      
          {{ (states.sensor.sa_consumption_power.state | int) - (states.sensor.sa_generation_power.state | int) }}
        icon_template: mdi:transmission-tower
        device_class: "power"
        attribute_templates:
          state_class: measurement
          time_stamp: "{{ states.sensor.sa_data_by_5min.state }}"

# -----------------------------------------------------------------------------
```
